# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '4.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtMultimedia import QMediaContent, QMediaPlayer
from PyQt5.QtCore import QUrl
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget
sizef = 1/2

class Ui_Julia(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200*sizef, 800*sizef)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(0, 170, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80*sizef, 86*sizef, 262*sizef, 32*sizef))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.callback)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320*sizef, 20*sizef, 582*sizef, 62*sizef))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520*sizef, 120*sizef, 650*sizef, 650*sizef))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("python/sine_wave.gif"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40*sizef, 120*sizef, 382*sizef, 82*sizef))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0*sizef, 320*sizef, 422*sizef, 42*sizef))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60*sizef, 384*sizef, 82*sizef, 32*sizef))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60*sizef, 446*sizef, 82*sizef, 32*sizef))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20*sizef, 500*sizef, 402*sizef, 82*sizef))
        self.label_7.setObjectName("label_7")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(140*sizef, 600*sizef, 182*sizef, 44*sizef))
        self.spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox.setObjectName("spinBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80*sizef, 660*sizef, 262*sizef, 32*sizef))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20*sizef, 720*sizef, 162*sizef, 32*sizef))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(260*sizef, 720*sizef, 162*sizef, 32*sizef))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(200*sizef, 380*sizef, 182*sizef, 44*sizef))
        self.spinBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_2.setMinimum(-2)
        self.spinBox_2.setMaximum(2)
        self.spinBox_2.setSingleStep(2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(200*sizef, 440*sizef, 182*sizef, 44*sizef))
        self.spinBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_4.setGeometry(QtCore.QRect(96*sizef, 270*sizef, 122*sizef, 44*sizef))
        self.spinBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10*sizef, 280*sizef, 82*sizef, 32*sizef))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0*sizef, 220*sizef, 422*sizef, 42*sizef))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(230*sizef, 280*sizef, 32*sizef, 32*sizef))
        self.label_10.setObjectName("label_10")
        self.spinBox_5 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_5.setGeometry(QtCore.QRect(276*sizef, 270*sizef, 122*sizef, 44*sizef))
        self.spinBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(410*sizef, 280*sizef, 32*sizef, 32*sizef))
        self.label_11.setObjectName("label_11")

        self.widget = QVideoWidget(MainWindow)
        self.widget.setGeometry(QtCore.QRect(100, 0, 1000, 1000))
        self.widget.setObjectName("widget")
        self.player = QMediaPlayer()
        self.player.setVideoOutput(self.widget)
        self.player.setMedia(QMediaContent(QUrl.fromLocalFile("C:/Users/novta/Desktop/python/mandelbrot1.mp4")))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def callback(self):
        self.player.setPosition(0) # to start at the beginning of the video every time
        self.widget.show()
        self.player.play()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Фракталы. Мандельброт"))
        self.pushButton.setText(_translate("MainWindow", "Теоретическая справка"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:(18*sizef)pt; font-weight:600;\">Множество Жюлиа</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:(14*sizef)pt; font-weight:600;\">Построение мнижества</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:(10*sizef)pt; text-decoration: underline;\">Введите координаты точки увеличения</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:(10*sizef)pt; font-weight:600;\">x = </span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:(10*sizef)pt; font-weight:600;\">y = </span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:1(10*sizef)pt; text-decoration: underline;\">Введите во сколько раз нужно приблизить </span></p><p align=\"center\"><span style=\" font-size:10pt; text-decoration: underline;\">фрактал</span></p><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Построить"))
        self.pushButton_3.setText(_translate("MainWindow", "Меню"))
        self.pushButton_4.setText(_translate("MainWindow", "Выход"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:(10*sizef)pt; font-weight:600;\">с = </span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:(10*sizef)pt; text-decoration: underline;\">Введите параметр с</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">+</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">*i</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Julia()
    ui.setupUi(MainWindow)
    MainWindow.show()

    # v = VideoPlayer()
    # b = QPushButton('start')
    # b.clicked.connect(v.callback)
    # b.show()
    sys.exit(app.exec_())
